cache:
  directories:
  - node_modules
env:
  global: 
sudo: false
language: node_js
node_js:
- '6'
before_install:
- npm install
script:
- npm start
notifications:
  slack:
    secure: QYJ/KdpV9uTsXJidxv/4Xrf0q/XtSJUyns2ZDHBnqNpfeAzqYPnqqnHHdrZZE2x/WaBU/7DOZeygvQuZL8y8kCZPqGV+ZUtQiFc2hjNTTQWKbuXkpZ/3jkAzOqE++vc6dnDfNuR227meaE+2OBB99BMH7XfK9kTTMX1RoeUM6HaOJOAqv3xqqDc9k9SoQO4haUbUDb47xQukIkuXvi20oE+AKB5DT/J9Vz0Zp9PqLVQFs2YcZsiTyCmdqRWTVifVfyxqyirP8d71WiXU0eMEJYz+yCsgz9O3UyUcxfJzNaQr+tdY9KhWexud5LtTdFqxpXyZ5w95ELPNPFWXFXIo4xHSEcyabeDvk0YOZ3pn8G0MzRzT8MJa06E5q4lkXrZrD8KkScdHlj12H9TooClK7a3g3/WkpruEyjTFg8KdOnwwu1XTVFc3Kg14AzFZuDf5lJCqSm75vDCqjpxi/Jzfvz6xj885YIMbDxMF0QSx7BpDtJlyLVi7EvEofXFKbBfUM6AS5Ug3pldybw86V17Qfc4b0zfCFFCWk0ElX2hwhefG9QNauqd5hFCwGoxdhe1S/l0aXCEaUJpbR6RE8qZfhSoCbv44i8qNhQp0jl2zie/B3fuzl0Q/kzIGgVk+owfxod33QWEI6kUaoKJiWk7UJ6+nh17pXYgMYRJPoXNDS3g=
