# ConfigMap - Start
kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-configmap
  namespace: default
data:
  # Please add values for labels that are in format "{...}" in this file. Other values should not be changed.

  # The connection string will be of format
  # "HostName={hubname}.azure-devices.net;SharedAccessKeyName={policy type};SharedAccessKey={Access Key};"
  # Policy Type can have following values: iothubowner, service, device, registryRead, registryReadWrite
  # The key will be shown in CLI window as output when remote-cli command has finished running.
  # Alternatively it can be accessed from http://portal.azure.com under {myResourceGroupName}
  # and resource type "Iot Hub" then "Shared access policies" menu.
  iothub.connstring: "{IoT Hub connection string}"

  # The connection string Document DB will be of format "AccountEndpoint={URI};AccountKey={Key};"
  # The key will be shown in CLI window as output when remote-cli command has finished running.
  # Alternatively it can be accessed from http://portal.azure.com under {myResourceGroupName}
  # and resource type "Azure Cosmos DB account" then "Keys" menu.
  docdb.connstring: "{DocumentDB connection string}"

  # Storage Adapter
  storageadapter.webservice.url: "http://storage-adapter-svc:9022/v1"
  storagadapter.collectionlink: "{Storage Adapter DocumentDB collection link}"

  # Stream Analytics
  iothubreact.hub.name: "{Iot Hub React name}"
  iothubreact.hub.endpoint: "{Iot Hub React endpoint}"
  iothubreact.hub.partitions: "{Iot Hub React partitions}"
  iothubreact.access.connstring: "{Iot Hub React connection string}"
  iothubreact.azureblob.account: "{Azure Blob account name}"
  iothubreact.azureblob.key: "{Azure Blob account key}"
  
  # Auth
  auth.aad.global.tenantid: "{AAD Tenant Id}"
  auth.aad.global.clientid: "{AAD Client Id}"
  auth.aad.global.loginuri: "https://login.microsoftonline.com/"
# ConfigMap - End

---

# Device Simulation - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-simulation
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-simulation
    spec:
      containers:
      - name: device-simulation-pod
        image: azureiotpcs/device-simulation-dotnet:latest
        ports:
        - containerPort: 9003
      env:
      - name: PCS_IOTHUB_CONNSTRING
        valueFrom:
          configMapKeyRef:
            name: deployment-configmap
            key: iothub.connstring
      - name: PCS_STORAGEADAPTER_WEBSERVICE_URL
        valueFrom:
          configMapKeyRef:
            name: deployment-configmap
            key: storageadapter.webservice.url
---
apiVersion: v1
kind: Service
metadata:
  name: device-simulation-svc
  labels:
    app: device-simulation
spec:
  type: NodePort
  ports:
  - port: 9003
  selector:
    app: device-simulation
# Device Simulation - End

---

# IotHub Manager - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iothub-manager
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: iothub-manager
    spec:
      containers:
      - name: iothub-manager-pod
        image: azureiotpcs/iothub-manager-dotnet:latest
        ports:
        - containerPort: 9002
        env:
        - name: PCS_IOTHUBMANAGER_WEBSERVICE_PORT
          value: "9002"
        - name: PCS_IOTHUB_CONNSTRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothub.connstring
---
apiVersion: v1
kind: Service
metadata:
  name: iothub-manager-svc
  labels:
    app: iothub-manager
spec:
  type: NodePort
  ports:
  - port: 9002
  selector:
    app: iothub-manager
# IotHub Manager - End

---

# Device Telemetry - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-telemetry
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-telemetry
    spec:
      containers:
      - name: device-telemetry-pod
        image: azureiotpcs/device-telemetry-java:latest
        ports:
        - containerPort: 9004
        env:
        - name: PCS_DEVICETELEMETRY_DOCUMENTDB_CONNSTRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: docdb.connstring
        - name: PCS_STORAGEADAPTER_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: storageadapter.webservice.url
---
apiVersion: v1
kind: Service
metadata:
  name: device-telemetry-svc
  labels:
    app: device-telemetry
spec:
  type: NodePort
  ports:
  - port: 9004
  selector:
    app: device-telemetry
# Device Telemetry - End

---

# Storage Adapter - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-adapter
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: storage-adapter
    spec:
      containers:
      - name: storage-adapter-pod
        image: azureiotpcs/pcs-storage-adapter-dotnet:latest
        ports:
        - containerPort: 9022
        env:
        - name: PCS_STORAGEADAPTER_WEBSERVICE_PORT
          value: "9022"
        - name: PCS_STORAGEADAPTER_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: storagadapter.collectionlink
        - name: PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: docdb.connstring
---
apiVersion: v1
kind: Service
metadata:
  name: storage-adapter-svc
  labels:
    app: storage-adapter
spec:
  type: NodePort
  ports:
  - port: 9022
  selector:
    app: storage-adapter
# Storage Adapter - End

---

# Stream Analytics - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-analytics
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: stream-analytics
    spec:
      containers:
      - name: stream-analytics-pod
        image: azureiotpcs/iot-stream-analytics-java:latest
        ports:
        - containerPort: 9023
        env:
        - name: PCS_STREAMANALYTICS_WEBSERVICE_PORT
          value: "9023"
        - name: PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: docdb.connstring
        - name: PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubreact.azureblob.account
        - name: PCS_IOTHUBREACT_AZUREBLOB_KEY
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubreact.azureblob.key
        - name: PCS_IOTHUBREACT_HUB_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubreact.hub.name
        - name: PCS_IOTHUBREACT_HUB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubreact.hub.endpoint
        - name: PCS_IOTHUBREACT_HUB_PARTITIONS
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubreact.hub.partitions
        - name: PCS_IOTHUBREACT_ACCESS_CONNSTRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubreact.access.connstring
---
apiVersion: v1
kind: Service
metadata:
  name: stream-analytics-svc
  labels:
    app: stream-analytics
spec:
  type: NodePort
  ports:
  - port: 9023
  selector:
    app: stream-analytics
# Stream Analytics - End

---

# UI Config - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui-config
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ui-config
    spec:
      containers:
      - name: ui-config-pod
        image: azureiotpcs/pcs-ui-config-dotnet:latest
        ports:
        - containerPort: 9005
        env:
        - name: PCS_UICONFIG_WEBSERVICE_PORT
          value: "9005"
        - name: PCS_STORAGEADAPTER_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: storageadapter.webservice.url
---
apiVersion: v1
kind: Service
metadata:
  name: ui-config-svc
  labels:
    app: ui-config
spec:
  type: NodePort
  ports:
  - port: 9005
  selector:
    app: ui-config
# UI Config - End

---

# Remote Monitoring WebUI - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: remote-monitoring-webui
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: remote-monitoring-webui
    spec:
      containers:
      - name: remote-monitoring-webui-pod
        image: azureiotpcs/pcs-remote-monitoring-webui:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: remote-monitoring-webui-svc
  labels:
    app: remote-monitoring-webui
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 80
  selector:
    app: remote-monitoring-webui
# Remote Monitoring WebUI - End

---

# Ingress - Start
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: remotemonitoring
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "{DNS}"
    http:
      paths:
      - path: /
        backend:
          serviceName: remote-monitoring-webui-svc
          servicePort: 9000
      - path: /iothubmanager
        backend:
          serviceName: iothub-manager-svc
          servicePort: 9002
      - path: /devicesimulation
        backend:
          serviceName: device-simulation-svc
          servicePort: 9003
      - path: /devicetelemetry
        backend:
          serviceName: device-telemetry-svc
          servicePort: 9004
      - path: /uiconfig
        backend:
          serviceName: ui-config-svc
          servicePort: 9005
# Ingress - End

---
# Auth - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-pod
        image: azureiotpcs/pcs-auth-dotnet:latest
        ports:
        - containerPort: 9001
        env:
        - name: PCS_AUTH_WEBSERVICE_PORT
          value: "9001"
        - name: PCS_AUTH_AAD_GLOBAL_LOGINURI
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: auth.aad.global.loginuri
        - name: PCS_AUTH_AAD_GLOBAL_TENANTID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: auth.aad.global.tenantid
        - name: PCS_AUTH_AAD_GLOBAL_CLIENTID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: auth.aad.global.clientid
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth
spec:
  type: NodePort
  ports:
  - port: 9001
  selector:
    app: auth
# Auth - End
