#!/usr/bin/env bash
set -x
export HOST_NAME="${1:-localhost}"
export APP_PORT="${2:-80}"
export APP_VERSION="${3:-latest}"

# HubManager environment
export PCS_IOTHUBMANAGER_WEBSERVICE_PORT=9002
export PCS_IOTHUB_CONN_STRING="$4"

# StorageAdapter environment
export PCS_STORAGEADAPTER_WEBSERVICE_PORT=9022
export PCS_STORAGEADAPTER_CONTAINER_NAME=pcsKeyValueStorage
export PCS_STORAGE_CONNSTRING="$5"

# UIConfig environment
export PCS_UICONFIG_WEBSERVICE_PORT=9005
export PCS_UICONFIG_CORS_WHITELIST=*
export PCS_STORAGEADAPTER_WEBSERVICE_URL="http://$HOST_NAME:$PCS_STORAGEADAPTER_WEBSERVICE_PORT/"

# DeviceSimulation environment
PCS_DEVICESIMULATION_WEBSERVICE_PORT=9003
PCS_IOTHUBMANAGER_WEBSERVICE_URL="http://$HOST_NAME:$PCS_IOTHUBMANAGER_WEBSERVICE_PORT/"

# Telemetry environment
PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT=9004
PCS_DEVICE_TELEMETRY_DOCDB_CONN_STRING=$PCS_STORAGE_CONNSTRING

# StreamAnalytics environment
PCS_STREAMANALYTICS_WEBSERVICE_PORT=9023
PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING=$PCS_STORAGE_CONNSTRING
PCS_IOTHUBREACT_ACCESS_CONNSTRING=$PCS_IOTHUB_CONN_STRING
PCS_IOTHUBREACT_HUB_NAME=iotpcsdev
PCS_IOTHUBREACT_HUB_ENDPOINT=Events
PCS_IOTHUBREACT_HUB_PARTITIONS=4

# Webui environment
export REACT_APP_UICONFIG_WEBSERVICE_URL="http://$HOST_NAME:$PCS_UICONFIG_WEBSERVICE_PORT/"
export REACT_APP_IOTHUBMANAGER_WEBSERVICE_URL="http://$HOST_NAME:$PCS_IOTHUBMANAGER_WEBSERVICE_PORT/"
export REACT_APP_DEVICESIMULATION_WEBSERVICE_URL="http://$HOST_NAME/"

docker run -d -p $PCS_IOTHUBMANAGER_WEBSERVICE_PORT:$PCS_IOTHUBMANAGER_WEBSERVICE_PORT \
    -e "PCS_IOTHUBMANAGER_WEBSERVICE_PORT=$PCS_IOTHUBMANAGER_WEBSERVICE_PORT" \
    -e "PCS_IOTHUB_CONN_STRING=$PCS_IOTHUB_CONN_STRING" \
    "azureiotpcs/iothub-manager-dotnet:$APP_VERSION"

docker run -d -p $PCS_STORAGEADAPTER_WEBSERVICE_PORT:$PCS_STORAGEADAPTER_WEBSERVICE_PORT \
    -e "PCS_STORAGEADAPTER_WEBSERVICE_PORT=$PCS_STORAGEADAPTER_WEBSERVICE_PORT" \
    -e "PCS_STORAGEADAPTER_CONTAINER_NAME=$PCS_STORAGEADAPTER_CONTAINER_NAME" \
    -e "PCS_STORAGE_CONNSTRING=$PCS_STORAGE_CONNSTRING" \
    "azureiotpcs/pcs-storage-adapter-dotnet:$APP_VERSION"

docker run -d -p $PCS_UICONFIG_WEBSERVICE_PORT:$PCS_UICONFIG_WEBSERVICE_PORT \
    -e "PCS_UICONFIG_WEBSERVICE_PORT=$PCS_UICONFIG_WEBSERVICE_PORT" \
    -e "PCS_UICONFIG_CORS_WHITELIST=$PCS_UICONFIG_CORS_WHITELIST" \
    -e "PCS_STORAGEADAPTER_WEBSERVICE_URL=$PCS_STORAGEADAPTER_WEBSERVICE_URL" \
    "azureiotpcs/pcs-ui-config-dotnet:$APP_VERSION"

docker run -d -p $PCS_DEVICESIMULATION_WEBSERVICE_PORT:$PCS_DEVICESIMULATION_WEBSERVICE_PORT \
    -e "PCS_DEVICESIMULATION_WEBSERVICE_PORT=$PCS_DEVICESIMULATION_WEBSERVICE_PORT" \
    -e "PCS_IOTHUBMANAGER_WEBSERVICE_URL=$PCS_IOTHUBMANAGER_WEBSERVICE_URL" \
    "azureiotpcs/device-simulation-dotnet:$APP_VERSION"

docker run -d -p $PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT:$PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT \
    -e "PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT=$PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT" \
    -e "PCS_DEVICE_TELEMETRY_DOCDB_CONN_STRING=$PCS_DEVICE_TELEMETRY_DOCDB_CONN_STRING" \
    "azureiotpcs/device-telemetry-java:$APP_VERSION"

docker run -d -p $PCS_STREAMANALYTICS_WEBSERVICE_PORT:$PCS_STREAMANALYTICS_WEBSERVICE_PORT \
    -e "PCS_STREAMANALYTICS_WEBSERVICE_PORT=$PCS_STREAMANALYTICS_WEBSERVICE_PORT" \
    -e "PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING=$PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING" \
    -e "PCS_IOTHUBREACT_ACCESS_CONNSTRING=$PCS_IOTHUBREACT_ACCESS_CONNSTRING" \
    -e "PCS_IOTHUBREACT_HUB_NAME=$PCS_IOTHUBREACT_HUB_NAME" \
    -e "PCS_IOTHUBREACT_HUB_ENDPOINT=$PCS_IOTHUBREACT_HUB_ENDPOINT" \
    -e "PCS_IOTHUBREACT_HUB_PARTITIONS=$PCS_IOTHUBREACT_HUB_PARTITIONS" \
    "azureiotpcs/iot-stream-analytics-java:$APP_VERSION"

docker run -d -p $APP_PORT:$APP_PORT \
    -e "REACT_APP_UICONFIG_WEBSERVICE_URL=$REACT_APP_UICONFIG_WEBSERVICE_URL" \
    -e "REACT_APP_IOTHUBMANAGER_WEBSERVICE_URL=$REACT_APP_IOTHUBMANAGER_WEBSERVICE_URL" \
    -e "REACT_APP_DEVICESIMULATION_WEBSERVICE_URL=$REACT_APP_DEVICESIMULATION_WEBSERVICE_URL" \
    "azureiotpcs/remote-monitoring-webui:$APP_VERSION"

set +x

