apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-pod
        image: azureiotpcs/pcs-auth-dotnet:testing
        ports:
        - containerPort: 9001
        env:
        - name: PCS_KEYVAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: keyvault.name
        - name: PCS_AAD_APPID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.audience
        - name: PCS_AAD_APPSECRET
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.serviceprincipal.secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth
spec:
  type: NodePort
  ports:
  - port: 9001
  selector:
    app: auth