apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telemetry
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
      - name: telemetry-pod
        image: azureiotpcs/telemetry-{runtime}:testing
        ports:
        - containerPort: 9004
        env:
        - name: PCS_KEYVAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: keyvault.name
        - name: PCS_AAD_APPID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.audience
        - name: PCS_AAD_APPSECRET
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.serviceprincipal.secret
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-svc
  labels:
    app: telemetry
spec:
  type: NodePort
  ports:
  - port: 9004
  selector:
    app: telemetry