apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-simulation
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-simulation
    spec:
      containers:
      - name: device-simulation-pod
        image: azureiotpcs/device-simulation-dotnet:DS-1.0.4
        ports:
        - containerPort: 9003
        env:
        - name: PCS_KEYVAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: keyvault.name
        - name: PCS_AAD_APPID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.audience
        - name: PCS_AAD_APPSECRET
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.serviceprincipal.secret
---
apiVersion: v1
kind: Service
metadata:
  name: device-simulation-svc
  labels:
    app: device-simulation
spec:
  type: NodePort
  ports:
  - port: 9003
  selector:
    app: device-simulation