apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: diagnostics
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: diagnostics
    spec:
      containers:
      - name: diagnostics-pod
        image: azureiotpcs/pcs-diagnostics-dotnet:Diagnostics-2.0.1
        ports:
        - containerPort: 9006
        env:
        - name: PCS_DIAGNOSTICS_WEBSERVICE_PORT
          value: "9006"
        - name: PCS_KEYVAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: keyvault.name
        - name: PCS_AAD_APPID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.audience
        - name: PCS_AAD_APPSECRET
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.serviceprincipal.secret
---
apiVersion: v1
kind: Service
metadata:
  name: diagnostics-svc
  labels:
    app: diagnostics
spec:
  type: NodePort
  ports:
  - port: 9006
  selector:
    app: diagnostics