apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iothub-manager
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: iothub-manager
    spec:
      containers:
      - name: iothub-manager-pod
        image: azureiotpcs/iothub-manager-{runtime}:testing
        ports:
        - containerPort: 9002
        env:
        - name: PCS_KEYVAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: keyvault.name
        - name: PCS_AAD_APPID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.audience
        - name: PCS_AAD_APPSECRET
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.serviceprincipal.secret
---
apiVersion: v1
kind: Service
metadata:
  name: iothub-manager-svc
  labels:
    app: iothub-manager
spec:
  type: NodePort
  ports:
  - port: 9002
  selector:
    app: iothub-manager