apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: remote-monitoring-webui
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: remote-monitoring-webui
    spec:
      containers:
      - name: remote-monitoring-webui-pod
        image: azureiotpcs/pcs-remote-monitoring-webui:testing
        ports:
        - containerPort: 10080
        env:
        - name: PCS_KEYVAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: keyvault.name
        - name: PCS_AAD_APPID
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.audience
        - name: PCS_AAD_APPSECRET
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: security.auth.serviceprincipal.secret
---
apiVersion: v1
kind: Service
metadata:
  name: remote-monitoring-webui-svc
  labels:
    app: remote-monitoring-webui
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 10080
  selector:
    app: remote-monitoring-webui