version: '2'

services:
  reverseproxy:
    image: azureiotpcs/simulation-api-gateway:millennium
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webui
      - devicesimulation
    volumes:
      - /app/certs:/app/certs:ro

  webui:
    image: azureiotpcs/device-simulation-webui:millennium
    depends_on:
      - devicesimulation
    volumes:
      - /app/webui-config.js:/app/build/webui-config.js:ro

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:millennium
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING=none
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
    # How one could mount custom device models. The path depends on
    # the Docker Compose version, see first line in this file.
    # Docker Compose v2:
    #volumes:
    #  - /absolute-path/my-device-models:/app/data:ro
    # Docker Compose v3 (which supports relative paths):
    #volumes:
    #  - ./my-device-models:/app/data:ro

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-dotnet:millennium
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
