# ConfigMap - Start
kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-configmap
  namespace: default
data:
  #IoT Hub Manager
  iothubmanager.webservice.url: "http://iothub-manager-svc:9002/v1"
  #The connection string will be of format "HostName={hubname}.azure-devices.net;SharedAccessKeyName={policy type};SharedAccessKey={Access Key}
  #Policy Type can have following values: iothubowner, service, device, registryRea, registryReadWrite
  #The key will be shown in CLI window as output when remote-cli command has finished running.
  #Alternatively it can be accessed from http://portal.azure.com under {myResourceGroupName} and resrouce type "Iot Hub" then "Shared access policies" menu.
  iothub.conn.string: "{Your IoT Hub connection string}"

  #The connection string Document DB will be of format "AccountEndpoint={URI};AccountKey={Key}"
  #The key will be shown in CLI window as output when remote-cli command has finished running.
  #Alternatively it can be accessed from http://portal.azure.com under {myResourceGroupName} and resrouce type "Azure Cosmos DB account" then "Keys" menu.
  docdb.conn.string: "{Your DocumentDB connection string}"
# ConfigMap - End

---

# Device Simulation - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-simulation
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-simulation
    spec:
      containers:
      - name: device-simulation-pod
        image: azureiotpcs/device-simulation-dotnet:latest
        ports:
        - containerPort: 9003
        env:
        - name: PCS_DEVICESIMULATION_WEBSERVICE_PORT
          value: "9003"
        - name: PCS_IOTHUBMANAGER_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubmanager.webservice.url
---
apiVersion: v1
kind: Service
metadata:
  name: device-simulation-svc
  labels:
    app: device-simulation
spec:
  type: NodePort
  ports:
  - port: 9003
  selector:
    app: device-simulation
# Device Simulation - End

---

# IotHub Manager - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iothub-manager
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: iothub-manager
    spec:
      containers:
      - name: iothub-manager-pod
        image: azureiotpcs/iothubmanager-dotnet:latest
        ports:
        - containerPort: 9002
        env:
        - name: PCS_IOTHUBMANAGER_WEBSERVICE_PORT
          value: "9002"
        - name: PCS_IOTHUB_CONN_STRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothub.conn.string
---
apiVersion: v1
kind: Service
metadata:
  name: iothub-manager-svc
  labels:
    app: iothub-manager
spec:
  type: NodePort
  ports:
  - port: 9002
  selector:
    app: iothub-manager
# IotHub Manager - End

---

# Device Telemetry - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-telemetry
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-telemetry
    spec:
      containers:
      - name: device-telemetry-pod
        image: azureiotpcs/device-telemetry-java:latest
        ports:
        - containerPort: 9004
        env:
        - name: PCS_DEVICE_TELEMETRY_WEBSERVICE_PORT
          value: "9004"
        - name: PCS_DEVICE_TELEMETRY_DOCDB_CONN_STRING
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: docdb.conn.string
---
apiVersion: v1
kind: Service
metadata:
  name: device-telemetry-svc
  labels:
    app: device-telemetry
spec:
  type: NodePort
  ports:
  - port: 9004
  selector:
    app: device-telemetry
# Device Telemetry - End

---

# Remote Monitoring WebUI - Start
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: remote-monitoring-webui
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: remote-monitoring-webui
    spec:
      containers:
      - name: remote-monitoring-webui-pod
        image: azureiotpcs/remote-monitoring-webui:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: remote-monitoring-webui-svc
  labels:
    app: remote-monitoring-webui
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 80
  selector:
    app: remote-monitoring-webui
# Remote Monitoring WebUI - End

---

# Ingress - Start
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: remotemonitoring
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "pcs-rm-v2.westus.cloudapp.azure.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: remote-monitoring-webui-svc
          servicePort: 9000
      - path: /hubmanager
        backend:
          serviceName: iothub-manager-svc
          servicePort: 9002
      - path: /devices
        backend:
          serviceName: device-simulation-svc
          servicePort: 9003
      - path: /telemetry
        backend:
          serviceName: device-telemetry-svc
          servicePort: 9004
# Ingress - End