#!/usr/bin/env bash
# Copyright (c) Microsoft. All rights reserved.
# Note: Windows Bash doesn't support shebang extra params
set -e

# Remove temporary files from the workspace

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
cd $APP_HOME

rm -fR build
rm -fR buildf
rm -fR node_modules
rm -fR publish

rm -f package-lock.json
